routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('email-verification/error', 'EmailVerificationController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'EmailVerificationController@getVerification')->name('email-verification.check');

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin\\'
], function() {
    Route::name('login')->get('login', 'Auth\LoginController@showLoginForm');
    Route::post('login','Auth\LoginController@login');

    Route::group(['middleware' => ['can:admin','isVerified']], function() {
        Route::name('logout')->post('logout','Auth\LoginController@logout');

        Route::get('dashboard', function() {
            return view('admin.dashboard');
        });
        Route::name('user_settings.edit')->get('users/settings', 'Auth\UserSettingsController@edit');
        Route::name('user_settings.update')->put('users/settings', 'Auth\UserSettingsController@update');
        Route::resource('users','UsersController');
        Route::resource('noticias','NoticiaController');
    });
});

app/Models/Noticia.php
<?php

namespace App\Models;

use Bootstrapper\Interfaces\TableInterface;
use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Noticia extends Model implements TableInterface
{
    use TransformableTrait;

    protected $fillable = ['titulo','descricao'];

    /**
     * A list of headers to be used when a table is displayed
     *
     * @return array
     */
    public function getTableHeaders()
    {
        return ['#', 'Titulo'];
    }

    /**
     * Get the value for a given header. Note that this will be the value
     * passed to any callback functions that are being used.
     *
     * @param string $header
     * @return mixed
     */
    public function getValueForHeader($header)
    {
        switch ($header) {
            case '#':
                return $this->id;
            case 'Titulo':
                return $this->titulo;
        }
    }
}

app/Http/Controllers/Admin/NoticiaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Forms\NoticiaForm;
use App\Models\Noticia;
use App\Repositories\NoticiaRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class NoticiaController extends Controller
{

    private $repository;

    /**
     * UsersController constructor.
     */
    public function __construct(NoticiaRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $noticias = $this->repository->paginate();
        return view('admin.noticias.index', compact('noticias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $form = \FormBuilder::create(NoticiaForm::class, [
            'url' => route('admin.noticias.store'),
            'method' => 'POST'
        ]);

        return view('admin.noticias.create', compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = \FormBuilder::create(NoticiaForm::class);

        if(!$form->isValid()){
            return redirect()
                ->back()
                ->withErrors($form->getErrors())
                ->withInput();
        }

        $data = $form->getFieldValues();
        $this->repository->create($data);

        $request->session()->flash('message','Notícia criada com sucesso.');

        return redirect()->route('admin.noticias.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Noticia $noticia)
    {
        return view('admin.noticias.show', compact('noticia'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Noticia $noticia)
    {
        $form = \FormBuilder::create(NoticiaForm::class, [
            'url' => route('admin.noticias.update', ['user' => $noticia->id]),
            'method' => 'PUT',
            'model' => $noticia
        ]);

        return view('admin.noticias.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form = \FormBuilder::create(NoticiaForm::class);

        if(!$form->isValid()){
            return redirect()
                ->back()
                ->withErrors($form->getErrors())
                ->withInput();
        }

        $data = array_except($form->getFieldValues(), ['password','role']);
        $this->repository->update($data, $id);

        $request->session()->flash('message','Notícia alterada com sucesso.');
        return redirect()->route('admin.noticias.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.noticias.index');
    }
}

app/Http/Controllers/Api/NoticiaController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Noticia;
use App\Repositories\NoticiaRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class NoticiaController extends Controller
{

    private $repository;

    /**
     * UsersController constructor.
     */
    public function __construct(NoticiaRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $noticias = $this->repository->paginate();
        return response()->json($noticias);
    }
//
//    /**
//     * Show the form for creating a new resource.
//     *
//     * @return \Illuminate\Http\Response
//     */
//    public function create()
//    {
//        $form = \FormBuilder::create(NoticiaForm::class, [
//            'url' => route('admin.noticias.store'),
//            'method' => 'POST'
//        ]);
//
//        return view('admin.noticias.create', compact('form'));
//    }
//
//    /**
//     * Store a newly created resource in storage.
//     *
//     * @param  \Illuminate\Http\Request  $request
//     * @return \Illuminate\Http\Response
//     */
//    public function store(Request $request)
//    {
//        $form = \FormBuilder::create(NoticiaForm::class);
//
//        if(!$form->isValid()){
//            return redirect()
//                ->back()
//                ->withErrors($form->getErrors())
//                ->withInput();
//        }
//
//        $data = $form->getFieldValues();
//        $this->repository->create($data);
//
//        $request->session()->flash('message','Notícia criada com sucesso.');
//
//        return redirect()->route('admin.noticias.index');
//    }
//
//    /**
//     * Display the specified resource.
//     *
//     * @param  int  $id
//     * @return \Illuminate\Http\Response
//     */
//    public function show(Noticia $noticia)
//    {
//        return view('admin.noticias.show', compact('noticia'));
//    }
//
//    /**
//     * Show the form for editing the specified resource.
//     *
//     * @param  int  $id
//     * @return \Illuminate\Http\Response
//     */
//    public function edit(Noticia $noticia)
//    {
//        $form = \FormBuilder::create(NoticiaForm::class, [
//            'url' => route('admin.noticias.update', ['user' => $noticia->id]),
//            'method' => 'PUT',
//            'model' => $noticia
//        ]);
//
//        return view('admin.noticias.edit', compact('form'));
//    }
//
//    /**
//     * Update the specified resource in storage.
//     *
//     * @param  \Illuminate\Http\Request  $request
//     * @param  int  $id
//     * @return \Illuminate\Http\Response
//     */
//    public function update(Request $request, $id)
//    {
//        $form = \FormBuilder::create(NoticiaForm::class);
//
//        if(!$form->isValid()){
//            return redirect()
//                ->back()
//                ->withErrors($form->getErrors())
//                ->withInput();
//        }
//
//        $data = array_except($form->getFieldValues(), ['password','role']);
//        $this->repository->update($data, $id);
//
//        $request->session()->flash('message','Notícia alterada com sucesso.');
//        return redirect()->route('admin.noticias.index');
//    }
//
//    /**
//     * Remove the specified resource from storage.
//     *
//     * @param  int  $id
//     * @return \Illuminate\Http\Response
//     */
//    public function destroy($id)
//    {
//        $this->repository->delete($id);
//        return redirect()->route('admin.noticias.index');
//    }
}

resources/views/admin/noticias/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h3>Nova Notícia</h3>
        {!! form($form->add('salve','submit', [
         'attr' => ['class' => 'btn btn-primary btn-block'],
            'label' => 'Salvar'
         ])) !!}
    </div>
</div>
@endsection

resources/views/admin/noticias/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h3>Editar Noticia</h3>
        {!! form($form->add('salve','submit', [
         'attr' => ['class' => 'btn btn-primary btn-block'],
            'label' => 'Salvar'
         ])) !!}
    </div>
</div>
@endsection

resources/views/admin/noticias/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h3>Lista de Notícias</h3>
        {!! Button::primary('Nova notícia')->asLinkTo(route('admin.noticias.create')) !!}
    </div>
    <div class="row">
       {!! Table::withContents($noticias->items())->striped()
            ->callback('Ações', function($field, $noticia) {
                $linkEdit = route('admin.noticias.edit', ['noticia' => $noticia->id]);
                $linkShow = route('admin.noticias.show', ['noticia' => $noticia->id]);
                return Button::link(Icon::create('pencil'))->asLinkTo($linkEdit) . "|" .
                        Button::link(Icon::create('remove'))->asLinkTo($linkShow);
            })
        !!}

        {!! $noticias->links() !!}
    </div>
</div>
@endsection

resources/views/admin/noticias/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h3>Visualizar Notícia</h3>

        <div class="row">
            {!! Button::primary('Editar')->asLinkTo(route('admin.noticias.edit', ['noticia' => $noticia->id])) !!}
            {!! Button::danger('Excluir')->asLinkTo(route('admin.noticias.destroy', ['noticia' => $noticia->id]))
                ->addAttributes(['onclick' => "event.preventDefault(); document.getElementById(\"form-delete\").submit();"])
            !!}
            <?php $formDelete = FormBuilder::plain([
                                                    'id' => 'form-delete',
                                                    'route' => ['admin.noticias.destroy', 'noticia' => $noticia->id],
                                                    'method' => 'DELETE',
                                                    'style' => 'display:none'
                                                    ]
                                                );
                    ?>
            {!! form($formDelete) !!}

            <br />
            <br />
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td scope="row">#</td>
                    <td>{{$noticia->id}}</td>
                </tr>
                <tr>
                    <td scope="row">Título</td>
                    <td>{{$noticia->titulo}}</td>
                </tr>
                <tr>
                    <td scope="row">Descrição</td>
                    <td>{{$noticia->descricao}}</td>
                </tr>

                </tbody>
            </table>
        </div>
        
    </div>
</div>
@endsection